version: 0.2

phases:
  install:
    runtime-version:
      java: corretto11
  pre_build:
    commands:
      - echo Logging in to Amz
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 186127023843.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=186127023843.dkr.ecr.us-east-2.amazonaws.com/cicdtest
  build:
    commands:
      - echo Build started on `date`
      - cd ./mainmod
      - mvn package -Pqa
      - ls
      - cd ..
      - docker build -t  $REPOSITORY_URI:latest.
      - docker tag $REPOSITORY_URI:latest:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"$REPOSITORY_URI:latest:latest"}' > imageDetail.json
artifacts:
  files:
    - imageDetail.json
    - taskdef.json
    - appspec.yaml